### ISSUE TITLE
tr.accessTokenExpiration might be null

### ISSUE THREAD

**Issue by witi83** [alexziskind1/nativescript-oauth#44]
I've encountered this error while developing:
```
JS: Error: Uncaught (in promise): TypeError: Cannot read property 'toString' of null
JS: TypeError: Cannot read property 'toString' of null
JS:     at Function.TnsOAuthTokenCache.getToken (file:///data/data/org.xxx.app/files/app/tns_modules/nativescript-oauth/tns-oauth-token-cache.js:15:73)
JS:     at Object.getTokenFromCache (file:///data/data/org.xxx.app/files/app/tns_modules/nativescript-oauth/tns-oauth.js:57:55)
JS:     at AuthHelperFacebook.AuthHelper (file:///data/data/org.xxx.app/files/app/tns_modules/nativescript-oauth/auth-helper.js:6:37)
JS:     at new AuthHelperFacebook (file:///data/data/org.xxx.app/files/app/tns_modules/nativescript-oauth/auth-helper-facebook.js:17:28)
JS:     at file:///data/data/org.xxx.app/files/app/tns_modules/nativescript-oauth/index.js:33:32
JS:     at new ZoneAwarePromise (file:///data/data/org.xxx.app/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:776:29)
JS:     at Object.initFacebook (file:///data/data/org.xxx.app/files/app/tns_modules/nativescript-oauth/index.js:27:12)
JS:     at Object.<anonymous> (file:///data/data/org.xxx.app/files/app/main.js:13:16)
JS:     at require (<anonymous>:1:266)
```
Since I haven't seen it in production by now, it might also be related to the auto-refresh mechanism of `tns run`. However, a null-check shouldn't be a bad idea at all.

**Comment by alexziskind1** [comment]
Hi Witold. Thanks for letting me know. A pull request would be awesome!
Alex

**Comment by witi83** [comment]
Hey @alexziskind1, sorry for the delay. There you go: https://github.com/alexziskind1/nativescript-oauth/pull/45

**Comment by alexziskind1** [comment]
Thanks Witold. I made a small fix, there was no variable 't', but it's good now.

**Comment by witi83** [comment]
Cool, thanks for merging!
